# Generated by Django 4.1.1 on 2022-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='N_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100, unique=True)),
                ('password1', models.TextField(max_length=100)),
                ('password2', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('role', models.TextField(max_length=100)),
            ],
        ),
    ]
