# Generated by Django 4.1.1 on 2022-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=True,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("screenshot", models.FileField(upload_to="media")),
                ("source", models.FileField(upload_to="media")),
                ("user_id", models.CharField(max_length=100)),
                ("status", models.CharField(default="pending", max_length=50)),
            ],
        ),
    ]
