# Generated by Django 4.1.1 on 2022-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="n_user",
            name="tsm",
            field=models.CharField(default="NONE", max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user", name="email", field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user",
            name="password1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user",
            name="password2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user",
            name="role",
            field=models.CharField(default="User", max_length=100),
        ),
        migrations.AlterField(
            model_name="n_user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
