# Generated by Django 4.1.1 on 2022-11-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_n_user_tsm_alter_n_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved')], default='pending', max_length=50),
        ),
    ]
